apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: chat-app
spec:
  type: NodePort # Exposes the API to external traffic (your browser)
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001 # Internal cluster port
      targetPort: 5001 # Container port (must match index.js)
      nodePort: 30001 # Fixed port for easy access (optional, can be random)
