apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chat-app
spec:
  type: NodePort # Exposes the UI to external traffic
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Nginx default port
      targetPort: 80
      nodePort: 30002 # Fixed port for easy access
